services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rouyi-fastapi:latest
    container_name: rouyi-fastapi
    command: .venv/bin/gunicorn main:app --env APP_ENV=prod --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:9099
    ports:
      - "9099:9099"
    volumes:
      - ${HOME}/data/ruoyi-fastapi-backend/logs:/app/logs
    restart: unless-stopped